name: Deploy Next.js to Staging Server

on:
  push:
    branches: ["stagging"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          password: ${{ secrets.STAGING_SERVER_PASSWORD }}
          port: 22
          script: |
            # Navigate to the correct project folder
            cd /var/www/cms-weberzio
            
            git pull origin stagging
            npm install
            npm run build